### PUT request to example server
PUT http://localhost:4000/patients/223e4567-e89b-12d3-a456-426614174010
Content-Type: application/json

{
  "name": "Mark Twain2",
  "email": "ertef@example.com",
  "address": "1234 street34",
  "dateOfBirth": "1997-05-04"
}
###